# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
