# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170222_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_time']},
        ),
    ]
